# Global registration with RANSAC
We are going to use [open3d](http://www.open3d.org/) to handle point clouds and generation of point clouds
We are importing the packages and defining a function which helps us drawing the point clouds.

In [1]:
import open3d as o3d
import numpy as np
import copy

# helper function for drawing
# If you want it to be more clear set recolor=True
def draw_registrations(source, target, transformation = None, recolor = False):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    if(recolor):
        source_temp.paint_uniform_color([1, 0.706, 0])
        target_temp.paint_uniform_color([0, 0.651, 0.929])
    if(transformation is not None):
        source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp])

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


We need to read in our pointclouds. For that we use the `io` module of the
open3d package (`o3d`). The following cell will open a window with a
visualization of both point clouds `source` and `target`.

Also, this page [Visualization - Open3D](http://open3d.org/html/tutorial/Basic/visualization.html)
contains some useful examples and instructions on how to use the viewer.

In [2]:
source = o3d.io.read_point_cloud("ICP/r1.pcd")
target = o3d.io.read_point_cloud("ICP/r2.pcd")

# Used for downsampling.
voxel_size = 0.05

# Show models side by side
draw_registrations(source, target)

### Finding features in pointclouds
When working on point clouds it can be beneficial to work on a downsampled version of the point cloud,
as it decreases the need of computation.

You can use [`pointcloud.voxel_down_sample()`](http://www.open3d.org/docs/latest/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.voxel_down_sample) where `pointcloud` is the name of your point cloud object. In our case, that would be `source` and `target`.

We also need to estimate the normals of the point cloud points using [`pointcloud.estimate_normals()`](http://www.open3d.org/docs/latest/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.voxel_down_sample)

**Task:** Find FPFH features or correspondances of the downsampled point clouds.
[`o3d.pipelines.registration.compute_fpfh_feature()`](http://www.open3d.org/docs/latest/python_api/open3d.pipelines.registration.compute_fpfh_feature.html)


In [3]:
####
# Downsample and find features here
####
vs = 0.05
source = source.voxel_down_sample(voxel_size=vs)
target = target.voxel_down_sample(voxel_size=vs)
# o3d.visualization.draw_geometries([source])
n1 = source.estimate_normals()
n2 = target.estimate_normals()

# Code
radius_feature = vs * 5
f_source = o3d.pipelines.registration.compute_fpfh_feature(source, o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100))
f_target = o3d.pipelines.registration.compute_fpfh_feature(target, o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100))

### RANSAC 
We will now attempt to use RANSAC to do a global registration of the two point clouds.

By using the function [`o3d.pipelines.registration.registration_ransac_based_on_feature_matching`](http://www.open3d.org/docs/latest/python_api/open3d.pipelines.registration.registration_ransac_based_on_feature_matching.html) from open3d, do the following:


Try to find the transformation from `r1.pcd` (`source`) to `r2.pcd` (`target`).
Attempt with point-to-point and point-to-plane
```Python
point_to_point =  o3d.pipelines.registration.TransformationEstimationPointToPoint(False)
point_to_plane =  o3d.pipelines.registration.TransformationEstimationPointToPlane()
```

When using RANSAC, focus on the arguments below. The rest are optional parameters.
```Python
ransac_result = o3d.registration.registration_ransac_based_on_feature_matching(
    source_sample, target_sample, 
    source_fpfh, target_fpfh, 
    distance_threshold,
    point_to_point)
```

In [4]:
####
# Call RANSAC here
####
point_to_point =  o3d.pipelines.registration.TransformationEstimationPointToPoint(False)
point_to_plane =  o3d.pipelines.registration.TransformationEstimationPointToPlane()
distance_threshold = vs * 1.5
ransac_result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
    source, target, 
    f_source, f_target, True,
    distance_threshold,
    point_to_point)
print(ransac_result.transformation)
draw_registrations(source, target, ransac_result.transformation, True)

[[-0.56858333  0.82256312  0.01014441  0.69409416]
 [-0.29946575 -0.21845494  0.92876138  1.15918183]
 [ 0.76618095  0.52504034  0.37053932 -1.64746226]
 [ 0.          0.          0.          1.        ]]


## Exercises
### A)
Can you get a decent transformation from r1 to r3? (check the ICP folder)
### B)
With the following checkers, can you get better results from RANSAC? Try tweaking the parameters of them. Can you make point-to-plane work? Do not spend too much time on this, if you can't manage, skip it. (I was not able to get a good fit.)

You can also try tweaking the `voxel_size`

```Python
corr_length = 0.9
distance_threshold = voxel_size * 1.5

c0 = o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(corr_length)
c1 = o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(distance_threshold)
c2 = o3d.pipelines.registration.CorrespondenceCheckerBasedOnNormal(0.095)

checker_list = [c0,c1,c2]

ransac_result = o3d.registration.registration_ransac_based_on_feature_matching(
    source_sample, target_sample, 
    source_fpfh, target_fpfh, 
    True,
    distance_threshold,
    point_to_point,
    checkers = checker_list)
```


In [5]:
# GET TRANSFORMATION from R1 to R3
r1 = o3d.io.read_point_cloud("ICP/r1.pcd")
r3 = o3d.io.read_point_cloud("ICP/r3.pcd")

vs = 0.05
r1 = r1.voxel_down_sample(voxel_size=vs)
r3 = r3.voxel_down_sample(voxel_size=vs)
draw_registrations(r1, r3)
# Code
point_to_point =  o3d.pipelines.registration.TransformationEstimationPointToPoint(False)
radius_feature = vs * 5
f_r1 = o3d.pipelines.registration.compute_fpfh_feature(r1, o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100))
f_r3 = o3d.pipelines.registration.compute_fpfh_feature(r3, o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100))
distance_threshold = vs * 1.5
ransac_result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
    r1, r3, 
    f_r1, f_r3, True,
    distance_threshold,
    point_to_point)
print(ransac_result.transformation)
draw_registrations(r1, r3, ransac_result.transformation, True)

[[ 0.40333658  0.9144853  -0.03219084 -0.5751598 ]
 [ 0.09464977 -0.00670336  0.99548806  0.25853439]
 [ 0.91014341 -0.4045636  -0.08925953  0.93468216]
 [ 0.          0.          0.          1.        ]]


In [6]:
corr_length = 0.9
distance_threshold = vs * 5

c0 = o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(corr_length)
c1 = o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(distance_threshold)
c2 = o3d.pipelines.registration.CorrespondenceCheckerBasedOnNormal(0.095)

checker_list = [c0,c1,c2]

ransac_result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
    r1, r3, 
    f_r1, f_r3, 
    True,
    distance_threshold,
    point_to_point,
    checkers = checker_list)
draw_registrations(r1, r3, ransac_result.transformation, True)